# app/routes/query_routes.py
from fastapi import APIRouter, HTTPException
from fastapi import Body
from fastapi.responses import JSONResponse
from typing import Dict, Any
import os
from app.core.file_manager import dataset_cache, load_excel_preview  # dataset_cache should exist
from app.core.llm_interpreter import call_llm_for_plan, call_llm_verifier
from app.core.executor import execute_plan
from app.core.logger import get_logger

logger = get_logger(__name__)
router = APIRouter()

@router.post("/query")
async def query_excel(payload: Dict[str, Any] = Body(...)):
    """Handles user queries on uploaded Excel files by generating, executing, and verifying the LLM generated plan."""
    logger.info(f"Received query request for file: {filename}")
    filename = payload.get("filename")
    sheet = payload.get("sheet")
    user_query = payload.get("query")
    if not filename or not user_query:
        raise HTTPException(status_code=400, detail="filename and query are required")

    if filename not in dataset_cache:
        ##where input files are saved.
        uploads_dir = "uploads"
        file_path = os.path.join(uploads_dir, filename)
        if not os.path.exists(file_path):
            raise HTTPException(status_code=404, detail="file not found")
        _ = load_excel_preview(file_path)

    sheets = dataset_cache.get(filename)
    if sheet is None:
        # pick first sheet if multiple sheets present
        sheet = list(sheets.keys())[0]
    if sheet not in sheets:
        raise HTTPException(status_code=404, detail="sheet not found in file")

    df = sheets[sheet]

    # Provide columns to LLM to improve results
    sample_columns = list(df.columns.astype(str))[:50]

    # 1) Ask LLM to produce plan for the user query
    try:
        plan = call_llm_for_plan(user_query, sample_columns=sample_columns)
    except ValueError as e:
        logger.error("LLM plan generation failed.")
        raise HTTPException(status_code=500, detail=str(e))

    # 2) Execute the plan generated by LLM
    other_tables = {k: v for k, v in sheets.items() if k != sheet}  # allow joins with other sheets in same file
    exec_out = execute_plan(df.copy(), plan, other_tables)

    if exec_out.get("status") != "ok":
        return JSONResponse(content={"status": "error", "message": exec_out.get("message")}, status_code=400)

    result_preview = exec_out.get("preview", [])

    # 3) Verification by LLM if the plan LLM opts for it
    if plan.get("verify", False):
        verifier = call_llm_verifier(user_query, plan, result_preview)
    else:
        verifier = {"ok": True, "note": "no verification requested"}

    # Return preview + operation metadata instead of full dataframe
    return JSONResponse(content={
        "status": "ok",
        "plan": plan,
        "message": exec_out.get("message"),
        "preview": result_preview,
        "verifier": verifier
    })
